app/__init__.py
from importlib import import_module

from flask import Flask
from flask_socketio import SocketIO

from app.core.socket import DockerSocket
from app.database import Base, engine
from app.config import Config

def create_app():
    app = Flask(__name__, static_folder='static')
    app.config.from_object(Config)

    register_blueprints(app)
    
    # Base.metadata.create_all(bind=engine)

    return app

def create_socketio(app):
    global socketio_instance

    socketio = SocketIO(app, cors_allowed_origins="*", async_mode='eventlet', engineio_logger=True)
    socketio.on_namespace(DockerSocket('/docker',socketio_instance=socketio))

    return socketio

def register_blueprints(app):
    for module_name in ('auth', 'home'):
        module = import_module('app.{}.routes'.format(module_name))
        app.register_blueprint(module.blueprint)

app/database/__init__.py
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base

from app.config import DatabaseConfig

Base = declarative_base()

engine = create_engine(
    DatabaseConfig.URL
)

SessionLocal = sessionmaker(
    autocommit=False,
    autoflush=False,
    bind=engine
)

app/database/repository/__init__.py
from sqlalchemy.orm import Session
from app.database import SessionLocal, Base
from sqlalchemy import desc


class BaseRepository:
    def __init__(self, db: Session = SessionLocal):
        self.db = db
        self.model = Base

    def create(self, obj):
        try:
            self.db.add(obj)
            self.db.commit()
            self.db.refresh(obj)

            return obj.id
        except Exception as e:
            print(e)
            self.db.rollback()

    def delete(self, id: int):
        try:
            obj = self.find_by_id(id)
            if obj:
                self.db.delete(obj)
                self.db.commit()
                return True
            else:
                return False
        except Exception as e:
            print(e)
            self.db.rollback()

    def delete_multiple(self, ids: list[int]):
        try:
            for id in ids:
                obj = self.find_by_id(id)
                if obj:
                    self.db.delete(obj)

            self.db.commit()
        except Exception as e:
            print(f"Error while deleting IDs: {e}")
            self.db.rollback()
            return False

        return True

    def update(self, id: int, updates: dict):
        try:
            obj = self.find_by_id(id)
            if obj:
                for key, value in updates.items():
                    if hasattr(obj, key):
                        setattr(obj, key, value)
                self.db.commit()
                self.db.refresh(obj)
                return obj
            else:
                print(f"Object with id {id} not found.")
                return None
        except Exception as e:
            print(e)
            self.db.rollback()

    def find_by_id(self, id: int):
        try:
            return self.db.query(self.model).filter(id==self.model.id).first()
        except Exception as e:
            print(e)
            self.db.rollback()

app/home/__init__.py
from flask import Blueprint

blueprint = Blueprint(
    'home_blueprint',
    __name__,
    url_prefix=''
)

app/home/routes.py
import docker
from flask import render_template, jsonify

from app.core.monitor import DockerMonitor
from app.home import blueprint

@blueprint.route('/', methods=['GET'])
def index():
    return render_template('pages/index.html', segment='dashboard')

@blueprint.route('/real-time', methods=['GET'])
def real_time():

    return render_template('pages/real-time.html', segment='real_time')



@blueprint.route('/profile', methods=['GET'])
def profile():
    return render_template('pages/index.html', segment='profile')

# @blueprint.app_template_filter('replace_value')
# def replace_value(value, args):
#   return value.replace(args, " ").title()

@blueprint.app_template_filter('replace_value')
def replace_value(value, args):
  return value.replace(args, " ").title()


# @blueprint.route('/proc', methods=['POST'])
# def proc():
#     container_list = ["postgres", "redis"]
#
#     try:
#         monitor = DockerMonitor()
#         res = monitor.state_(container_list)
#         return jsonify({"code": 200,"data":res}), 200
#
#         # while True:
#         #     print(f"Original list: {container_list}")
#         #     shutdown_list = monitor.state_(container_list)
#         #     print(f"Remaining containers: {shutdown_list}")
#         #     time.sleep(1)
#     except docker.errors.DockerException as e:
#         print(f"Failed to connect to Docker. {e}")

app/templates/accounts/login.html
{% extends "layouts/base-auth.html" %}

{% block content %}

  <main class="main-content  mt-0">
    <section>
      <div class="page-header min-vh-75">
        <div class="container">
          <div class="row">
            <div class="col-xl-4 col-lg-5 col-md-6 d-flex flex-column mx-auto">
              <div class="card card-plain mt-8">
                <div class="card-header pb-0 text-left bg-transparent">
                  <h3 class="font-weight-bolder text-info text-gradient">Welcome back</h3>
                  <p class="mb-0">Enter your email and password to sign in</p>
                </div>
                <div class="card-body">
                  {% if is_github %}
                  <div class="text-center">
                    <a class="btn btn-outline-light" href="{{ url_for('github.login') }}">
                      <svg aria-hidden="true" class="octicon octicon-mark-github" width="24px" height="32px" version="1.1" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path>
                      </svg>
                    </a>
                  </div>
                  {% endif %}
                  <form role="form" method="post">
                    {{ form.hidden_tag() }}

                    {% if msg %}
                      <span class="d-block text-danger mb-3">{{ msg | safe }}</span>
                    {% endif %} 

                    <label>Username</label>
                    <div class="mb-3">
                      {{ form.username(placeholder="Username or eMail", class="form-control") }}
                    </div>

                    <label>Password</label>
                    <div class="mb-3">
                      {{ form.password(placeholder="Password", class="form-control", type="password") }}
                    </div>

                    <div class="d-flex align-items-center justify-content-between">
                      <div class="form-check form-switch">
                        <input class="form-check-input" type="checkbox" id="rememberMe" checked="">
                        <label class="form-check-label" for="rememberMe">Remember me</label>
                      </div>
                    </div>
                    <div class="text-center">
                      <button type="submit" name="login" class="btn bg-gradient-info w-100 mt-4 mb-0">Sign in</button>
                    </div>
                  </form>
                </div>
                <div class="card-footer text-center pt-0 px-lg-2 px-1">
                  <p class="mb-4 text-sm mx-auto">
                    Don't have an account?
                    <a href="{{ url_for('authentication_blueprint.register') }}" class="text-info text-gradient font-weight-bold">Sign up</a>
                  </p>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="oblique position-absolute top-0 h-100 d-md-block d-none me-n8">
                <div class="oblique-image bg-cover position-absolute fixed-top ms-auto h-100 z-index-0 ms-n6" style="background-image:url('{{ url_for('static', filename='img/curved-images/curved6.jpg') }}')"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
  
{% endblock content %}

app/templates/accounts/password_reset.html
{% extends "layouts/base-auth.html" %}
{% load static %}

{% block content %}

  <main class="main-content  mt-0">
    <section>
      <div class="page-header min-vh-75">
        <div class="container">
          <div class="row">
            <div class="col-xl-4 col-lg-5 col-md-6 d-flex flex-column mx-auto">
              <div class="card card-plain mt-8">
                <div class="card-header pb-0 text-left bg-transparent">
                  <h3 class="font-weight-bolder text-info text-gradient">Reset Password</h3>
                  <p class="mb-0">Enter your email to reset password</p>
                </div>
                <div class="card-body">
                  <form role="form" method="post">
                    {% csrf_token %}

                    {% if form.non_field_errors %}
                      {% for error in form.non_field_errors %}
                        <span class="d-block text-danger mb-3">{{ error }}</span>
                      {% endfor %}
                    {% endif %}

                    {% for field in form %}
                      <label>{{ field.label }}</label>
                      <div class="mb-3">
                        {{ field }}
                      </div>
                    {% endfor %}
                    <div class="text-center">
                      <button type="submit" class="btn bg-gradient-info w-100 mt-4 mb-0">Reset</button>
                    </div>
                  </form>
                </div>
                <div class="card-footer text-center pt-0 px-lg-2 px-1">
                  <p class="mb-4 text-sm mx-auto">
                    Remember password?
                    <a href="{% url "login" %}" class="text-info text-gradient font-weight-bold">Sign in</a>
                  </p>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="oblique position-absolute top-0 h-100 d-md-block d-none me-n8">
                <div class="oblique-image bg-cover position-absolute fixed-top ms-auto h-100 z-index-0 ms-n6" style="background-image:url('{% static "img/curved-images/curved6.jpg" %}')"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
  
{% endblock content %}

app/templates/accounts/password_reset_complete.html
{% extends "layouts/base-auth.html" %}
{% load static %}

{% block content %}

  <main class="main-content  mt-0">
    <section>
      <div class="page-header min-vh-75">
        <div class="container">
          <div class="row">
            <div class="col-xl-4 col-lg-5 col-md-6 d-flex flex-column mx-auto">
              <div class="card card-plain mt-8">
                <div class="card-header pb-0 text-left bg-transparent">
                  <h3 class="font-weight-bolder text-info text-gradient">Password Changed</h3>
                  <p class="mb-4">Your password has been changed successfully.</p>
                  <p class="text-sm">
                    <a href="{% url "login" %}" class="text-info text-gradient font-weight-bold">Login again</a>
                  </p>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="oblique position-absolute top-0 h-100 d-md-block d-none me-n8">
                <div class="oblique-image bg-cover position-absolute fixed-top ms-auto h-100 z-index-0 ms-n6" style="background-image:url('{% static "img/curved-images/curved6.jpg" %}')"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
  
{% endblock content %}

app/templates/accounts/password_reset_confirm.html
{% extends "layouts/base-auth.html" %}
{% load static %}

{% block content %}

  <main class="main-content  mt-0">
    <section>
      <div class="page-header min-vh-75">
        <div class="container">
          <div class="row">
            <div class="col-xl-4 col-lg-5 col-md-6 d-flex flex-column mx-auto">
              <div class="card card-plain mt-8">
                <div class="card-header pb-0 text-left bg-transparent">
                  <h3 class="font-weight-bolder text-info text-gradient">Reset Password</h3>
                  <p class="mb-0">Enter new password here</p>
                </div>
                <div class="card-body">
                  <form role="form" method="post">
                    {% csrf_token %}

                    {% if form.non_field_errors %}
                      {% for error in form.non_field_errors %}
                        <span class="d-block text-danger mb-3">{{ error }}</span>
                      {% endfor %}
                    {% endif %}

                    {% for field in form %}
                      <label>{{ field.label }}</label>
                      <div class="mb-3">
                        {{ field }}
                        <span class="d-block mt-1 text-danger">{{ field.errors }}</span>
                      </div>
                    {% endfor %}
                    <div class="text-center">
                      <button type="submit" class="btn bg-gradient-info w-100 mt-4 mb-0">Reset</button>
                    </div>
                  </form>
                </div>
                <div class="card-footer text-center pt-0 px-lg-2 px-1">
                  <p class="mb-4 text-sm mx-auto">
                    Remember password?
                    <a href="{% url "login" %}" class="text-info text-gradient font-weight-bold">Sign in</a>
                  </p>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="oblique position-absolute top-0 h-100 d-md-block d-none me-n8">
                <div class="oblique-image bg-cover position-absolute fixed-top ms-auto h-100 z-index-0 ms-n6" style="background-image:url('{% static "img/curved-images/curved6.jpg" %}')"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
  
{% endblock content %}

app/templates/accounts/password_reset_done.html
{% extends "layouts/base-auth.html" %}
{% load static %}

{% block content %}

  <main class="main-content  mt-0">
    <section>
      <div class="page-header min-vh-75">
        <div class="container">
          <div class="row">
            <div class="col-xl-4 col-lg-5 col-md-6 d-flex flex-column mx-auto">
              <div class="card card-plain mt-8">
                <div class="card-header pb-0 text-left bg-transparent">
                  <h3 class="font-weight-bolder text-info text-gradient">Email Sent</h3>
                  <p class="mb-4">An email has been sent to your email address. Please click the link and reset your password.</p>
                  <p class="text-sm">
                    Remember password?
                    <a href="{% url "login" %}" class="text-info text-gradient font-weight-bold">Sign in</a>
                  </p>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="oblique position-absolute top-0 h-100 d-md-block d-none me-n8">
                <div class="oblique-image bg-cover position-absolute fixed-top ms-auto h-100 z-index-0 ms-n6" style="background-image:url('{% static "img/curved-images/curved6.jpg" %}')"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
  
{% endblock content %}

app/templates/includes/configurator.html
<div class="fixed-plugin">
    <a class="fixed-plugin-button text-dark position-fixed px-3 py-2">
      <i class="fa fa-cog py-2"> </i>
    </a>
    <div class="card shadow-lg ">
      <div class="card-header pb-0 pt-3 ">
        <div class="float-start">
          <h5 class="mt-3 mb-0">Soft UI Configurator</h5>
          <p>See our dashboard options.</p>
        </div>
        <div class="float-end mt-4">
          <button class="btn btn-link text-dark p-0 fixed-plugin-close-button">
            <i class="fa fa-close"></i>
          </button>
        </div>
        <!-- End Toggle Button -->
      </div>
      <hr class="horizontal dark my-1">
      <div class="card-body pt-sm-3 pt-0">
        <!-- Sidebar Backgrounds -->
        <div>
          <h6 class="mb-0">Sidebar Colors</h6>
        </div>
        <a href="javascript:void(0)" class="switch-trigger background-color">
          <div class="badge-colors my-2 text-start">
            <span class="badge filter bg-primary active" data-color="primary" onclick="sidebarColor(this)"></span>
            <span class="badge filter bg-gradient-dark" data-color="dark" onclick="sidebarColor(this)"></span>
            <span class="badge filter bg-gradient-info" data-color="info" onclick="sidebarColor(this)"></span>
            <span class="badge filter bg-gradient-success" data-color="success" onclick="sidebarColor(this)"></span>
            <span class="badge filter bg-gradient-warning" data-color="warning" onclick="sidebarColor(this)"></span>
            <span class="badge filter bg-gradient-danger" data-color="danger" onclick="sidebarColor(this)"></span>
          </div>
        </a>
        <!-- Sidenav Type -->
        <div class="mt-3">
          <h6 class="mb-0">Sidenav Type</h6>
          <p class="text-sm">Choose between 2 different sidenav types.</p>
        </div>
        <div class="d-flex">
          <button class="btn btn-primary w-100 px-3 mb-2 active" data-class="bg-transparent" onclick="sidebarType(this)">Transparent</button>
          <button class="btn btn-primary w-100 px-3 mb-2 ms-2" data-class="bg-white" onclick="sidebarType(this)">White</button>
        </div>
        <p class="text-sm d-xl-none d-block mt-2">You can change the sidenav type just on desktop view.</p>
        <!-- Navbar Fixed -->
        <div class="mt-3">
          <h6 class="mb-0">Navbar Fixed</h6>
        </div>
        <div class="form-check form-switch ps-0">
          <input class="form-check-input mt-1 ms-auto" type="checkbox" id="navbarFixed" onclick="navbarFixed(this)">
        </div>
        <hr class="horizontal dark my-sm-4">
        <a class="btn bg-gradient-dark w-100" href="https://app-generator.dev/product/soft-ui-dashboard/flask/">Download</a>
        <a class="btn btn-outline-dark w-100" href="https://app-generator.dev/docs/products/flask/soft-ui-dashboard/index.html">Documentation</a>
        <div class="w-100 text-center">
          <a class="github-button" href="https://github.com/app-generator/flask-soft-ui-dashboard" data-icon="octicon-star" data-size="large" data-show-count="true" aria-label="Star creativetimofficial/soft-ui-dashboard on GitHub">Star</a>
          <h6 class="mt-3">Thank you for sharing!</h6>
          <a href="https://twitter.com/intent/tweet?text=Check%20Soft%20UI%20Dashboard%20made%20by%20%40CreativeTim%20%23webdesign%20%23dashboard%20%23bootstrap5&amp;url=https%3A%2F%2Fwww.creative-tim.com%2Fproduct%2Fsoft-ui-dashboard" class="btn btn-dark mb-0 me-2" target="_blank">
            <i class="fab fa-twitter me-1" aria-hidden="true"></i> Tweet
          </a>
          <a href="https://www.facebook.com/sharer/sharer.php?u=https://app-generator.dev/product/soft-ui-dashboard/flask/" class="btn btn-dark mb-0 me-2" target="_blank">
            <i class="fab fa-facebook-square me-1" aria-hidden="true"></i> Share
          </a>
        </div>
      </div>
    </div>
</div>

app/templates/includes/footer.html
<footer class="footer pt-3  ">
    <div class="container-fluid">
      <div class="row align-items-center justify-content-lg-between">
        <div class="col-lg-6 mb-lg-0 mb-4">
          <div class="copyright text-center text-sm text-muted text-lg-start">
            &copy; Creative-Tim coded by <span class="font-weight-bold">Telepix</span>.
          </div>
        </div>
        <div class="col-lg-6">
          <ul class="nav nav-footer justify-content-center justify-content-lg-end">
            <li class="nav-item">
              <a href="https://app-generator.dev/product/soft-ui-dashboard/flask/" class="nav-link text-muted">Download</a>
            </li>
            <li class="nav-item">
              <a href="https://app-generator.dev/docs/products/flask/soft-ui-dashboard/index.html" class="nav-link text-muted">Documentation</a>
            </li>
            <li class="nav-item">
              <a href="https://app-generator.dev/product/soft-ui-dashboard-pro/flask/" class="nav-link text-muted">PRO Version</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
</footer>

app/templates/includes/head.html
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="apple-touch-icon" sizes="76x76" href="{{ url_for('static', filename='img/docker-logo-favicon-180x180.png') }}">

<link rel="icon" type="image/png" href="{{ url_for('static', filename='img/docker-logo-favicon-32x32.png') }}">
<link rel="icon" type="image/png" href="{{ url_for('static', filename='img/docker-logo-favicon-192x192.png') }}">

<title>
  Docker Dashboard
</title>

<!--     Fonts and icons     -->
<link href="https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700,800" rel="stylesheet" />
<!-- Nucleo Icons -->
<link href="https://demos.creative-tim.com/argon-dashboard-pro/assets/css/nucleo-icons.css" rel="stylesheet" />
<link href="https://demos.creative-tim.com/argon-dashboard-pro/assets/css/nucleo-svg.css" rel="stylesheet" />
<!-- Font Awesome Icons -->
<script defer src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.0/js/all.min.js" crossorigin="anonymous"></script>
<!-- CSS Files -->
<link id="pagestyle" href="{{ url_for('static', filename='css/soft-ui-dashboard.css') }}?v=1.1.0" rel="stylesheet" />

app/templates/includes/sidebar.html
<aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3 " id="sidenav-main">
    <div class="sidenav-header">
      <i class="fas fa-times p-3 cursor-pointer text-secondary opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
      <a class="navbar-brand m-0" href="{{ url_for('home_blueprint.index') }}">
        <img src="{{ url_for('static', filename='img/docker_icon.png') }}" class="navbar-brand-img h-100" alt="main_logo">
        <span class="ms-1 font-weight-bold">Docker Dashboard</span>
      </a>
    </div>
    <hr class="horizontal dark mt-0">
    <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
      <ul class="navbar-nav">

        <li class="nav-item">
          <a class="nav-link {% if segment == 'dashboard' %}active{% endif %}" href="{{ url_for('home_blueprint.index') }}">
            <div class="icon icon-shape icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
              <svg width="12px" height="12px" viewBox="0 0 45 40" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                <title>shop </title>
                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                  <g transform="translate(-1716.000000, -439.000000)" fill="#FFFFFF" fill-rule="nonzero">
                    <g transform="translate(1716.000000, 291.000000)">
                      <g transform="translate(0.000000, 148.000000)">
                        <path class="color-background opacity-6" d="M46.7199583,10.7414583 L40.8449583,0.949791667 C40.4909749,0.360605034 39.8540131,0 39.1666667,0 L7.83333333,0 C7.1459869,0 6.50902508,0.360605034 6.15504167,0.949791667 L0.280041667,10.7414583 C0.0969176761,11.0460037 -1.23209662e-05,11.3946378 -1.23209662e-05,11.75 C-0.00758042603,16.0663731 3.48367543,19.5725301 7.80004167,19.5833333 L7.81570833,19.5833333 C9.75003686,19.5882688 11.6168794,18.8726691 13.0522917,17.5760417 C16.0171492,20.2556967 20.5292675,20.2556967 23.494125,17.5760417 C26.4604562,20.2616016 30.9794188,20.2616016 33.94575,17.5760417 C36.2421905,19.6477597 39.5441143,20.1708521 42.3684437,18.9103691 C45.1927731,17.649886 47.0084685,14.8428276 47.0000295,11.75 C47.0000295,11.3946378 46.9030823,11.0460037 46.7199583,10.7414583 Z"></path>
                        <path class="color-background" d="M39.198,22.4912623 C37.3776246,22.4928106 35.5817531,22.0149171 33.951625,21.0951667 L33.92225,21.1107282 C31.1430221,22.6838032 27.9255001,22.9318916 24.9844167,21.7998837 C24.4750389,21.605469 23.9777983,21.3722567 23.4960833,21.1018359 L23.4745417,21.1129513 C20.6961809,22.6871153 17.4786145,22.9344611 14.5386667,21.7998837 C14.029926,21.6054643 13.533337,21.3722507 13.0522917,21.1018359 C11.4250962,22.0190609 9.63246555,22.4947009 7.81570833,22.4912623 C7.16510551,22.4842162 6.51607673,22.4173045 5.875,22.2911849 L5.875,44.7220845 C5.875,45.9498589 6.7517757,46.9451667 7.83333333,46.9451667 L19.5833333,46.9451667 L19.5833333,33.6066734 L27.4166667,33.6066734 L27.4166667,46.9451667 L39.1666667,46.9451667 C40.2482243,46.9451667 41.125,45.9498589 41.125,44.7220845 L41.125,22.2822926 C40.4887822,22.4116582 39.8442868,22.4815492 39.198,22.4912623 Z"></path>
                      </g>
                    </g>
                  </g>
                </g>
              </svg>
            </div>
            <span class="nav-link-text ms-1">Dashboard</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if segment == 'real_time' %}active{% endif %}" href="{{ url_for('home_blueprint.real_time') }}">
            <div class="icon icon-shape icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
              <svg width="12px" height="12px" viewBox="0 0 42 42" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                <title>office</title>
                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                  <g transform="translate(-1869.000000, -293.000000)" fill="#FFFFFF" fill-rule="nonzero">
                    <g transform="translate(1716.000000, 291.000000)">
                      <g id="office" transform="translate(153.000000, 2.000000)">
                        <path class="color-background opacity-6" d="M12.25,17.5 L8.75,17.5 L8.75,1.75 C8.75,0.78225 9.53225,0 10.5,0 L31.5,0 C32.46775,0 33.25,0.78225 33.25,1.75 L33.25,12.25 L29.75,12.25 L29.75,3.5 L12.25,3.5 L12.25,17.5 Z"></path>
                        <path class="color-background" d="M40.25,14 L24.5,14 C23.53225,14 22.75,14.78225 22.75,15.75 L22.75,38.5 L19.25,38.5 L19.25,22.75 C19.25,21.78225 18.46775,21 17.5,21 L1.75,21 C0.78225,21 0,21.78225 0,22.75 L0,40.25 C0,41.21775 0.78225,42 1.75,42 L40.25,42 C41.21775,42 42,41.21775 42,40.25 L42,15.75 C42,14.78225 41.21775,14 40.25,14 Z M12.25,36.75 L7,36.75 L7,33.25 L12.25,33.25 L12.25,36.75 Z M12.25,29.75 L7,29.75 L7,26.25 L12.25,26.25 L12.25,29.75 Z M35,36.75 L29.75,36.75 L29.75,33.25 L35,33.25 L35,36.75 Z M35,29.75 L29.75,29.75 L29.75,26.25 L35,26.25 L35,29.75 Z M35,22.75 L29.75,22.75 L29.75,19.25 L35,19.25 L35,22.75 Z"></path>
                      </g>
                    </g>
                  </g>
                </g>
              </svg>
            </div>
            <span class="nav-link-text ms-1">실시간 현황</span>
          </a>
        </li>
      </ul>
    </div>
    <div class="sidenav-footer mx-3 ">
{#      <a class="btn btn-primary mt-3 w-100" href="https://app-generator.dev/product/soft-ui-dashboard-pro/flask/">Upgrade to PRO</a>#}
    </div>
</aside>